const PROFESSORS = ['김용하', '김태곤', '이준호', '김일국', '김성은'];

const CATEGORY_BASELINE_MONTHLY = {
  '2025-09': {
    headneck_congenital: 0,
    headneck_tumor: 3,
    headneck_trauma_infection_etc: 22,
    breast_trunk_leg_congenital: 0,
    breast_trunk_leg_tumor: 0,
    breast_trunk_leg_trauma_infection_etc: 35,
    hand_upper_congenital: 0,
    hand_upper_tumor: 1,
    hand_upper_trauma_infection_etc: 3,
    skin_tumor: 9,
    cosmetic: 15,
  },
  '2025-10': {
    headneck_congenital: 0,
    headneck_tumor: 3,
    headneck_trauma_infection_etc: 19,
    breast_trunk_leg_congenital: 0,
    breast_trunk_leg_tumor: 7,
    breast_trunk_leg_trauma_infection_etc: 21,
    hand_upper_congenital: 0,
    hand_upper_tumor: 3,
    hand_upper_trauma_infection_etc: 1,
    skin_tumor: 10,
    cosmetic: 10,
  },
  '2025-11': {
    headneck_congenital: 0,
    headneck_tumor: 5,
    headneck_trauma_infection_etc: 14,
    breast_trunk_leg_congenital: 1,
    breast_trunk_leg_tumor: 8,
    breast_trunk_leg_trauma_infection_etc: 22,
    hand_upper_congenital: 0,
    hand_upper_tumor: 1,
    hand_upper_trauma_infection_etc: 0,
    skin_tumor: 9,
    cosmetic: 11,
  },
  '2025-12': {
    headneck_congenital: 0,
    headneck_tumor: 3,
    headneck_trauma_infection_etc: 12,
    breast_trunk_leg_congenital: 1,
    breast_trunk_leg_tumor: 1,
    breast_trunk_leg_trauma_infection_etc: 9,
    hand_upper_congenital: 0,
    hand_upper_tumor: 0,
    hand_upper_trauma_infection_etc: 0,
    skin_tumor: 14,
    cosmetic: 24,
  },
  '2026-01': {
    headneck_congenital: 0,
    headneck_tumor: 1,
    headneck_trauma_infection_etc: 18,
    breast_trunk_leg_congenital: 0,
    breast_trunk_leg_tumor: 2,
    breast_trunk_leg_trauma_infection_etc: 15,
    hand_upper_congenital: 0,
    hand_upper_tumor: 0,
    hand_upper_trauma_infection_etc: 0,
    skin_tumor: 10,
    cosmetic: 21,
  },
};

module.exports = { PROFESSORS, CATEGORY_BASELINE_MONTHLY };
